# Generated by Django 2.2.5 on 2020-01-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BarsTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='rankOfHandShadow',
            field=models.BooleanField(default=False),
        ),
    ]
